name: deploy
on:
    push:
        branches: [main]
env:
    NEXT_PUBLIC_PORT: ${{secrets.NEXT_PUBLIC_PORT}}
    NEXT_PUBLIC_GITHUB_CLIENT_ID: ${{secrets.NEXT_PUBLIC_GITHUB_CLIENT_ID}}
    NEXT_PUBLIC_GITHUB_CLIENT_SECRET: ${{secrets.NEXT_PUBLIC_GITHUB_CLIENT_SECRET}}
    NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID}}
    NEXT_PUBLIC_GOOGLE_REDIRECT: ${{secrets.NEXT_PUBLIC_GOOGLE_REDIRECT}}
    NEXT_PUBLIC_KAKAO_CLIENT_ID: ${{secrets.NEXT_PUBLIC_KAKAO_CLIENT_ID}}
    NEXT_PUBLIC_KAKAO_REDIRECT: ${{secrets.NEXT_PUBLIC_KAKAO_REDIRECT}}
    NEXT_PUBLIC_API_SERVER: ${{secrets.NEXT_PUBLIC_API_SERVER}}
    NEXT_PUBLIC_COOKIE_MAX_AGE: ${{secrets.NEXT_PUBLIC_COOKIE_MAX_AGE}}
jobs:
    deploy:
        runs-on: ["self-hosted", "Linux", "X64"]
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - name: Install npm packages
              run: npm ci
            - name: Build
              run: npm run build
            - name: Kill process
              run: fuser -k ${{ secrets.NEXT_PUBLIC_PORT }}/tcp || true
            - name: Run background
              run: RUNNER_TRACKING_ID="" && nohup npm run start:prod &
